# Site settings
title: Shire Jiang
email: shirejiang@gmail.com
username: shirejiang
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://shirejiang.com"

# Build settings
markdown: kramdown
permalink: pretty
