# Site settings
title: Shire Jiang
email: shirejiang@gmail.com
username: shirejiang
description: "Blog site of Shire Jiang. We are always looking for something beautiful."
baseurl: ""
url: "http://shirejiang.com"

# Build settings
markdown: kramdown
permalink: pretty

paginate: 1
paginate_path: "blog/page:num"